theme: jekyll-theme-hacker
collections:
  notes:
    output: true
    permalink: :title.html
  radios:
    output: true
    permalink: /radio/:title.html
defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: post
