theme: jekyll-theme-midnight
collections:
        site:
                output: true
                permalink: :title.html
defaults:
  - scope:
      path: ""
      type: site
    values:
      layout: post
