theme: jekyll-theme-midnight
collections:
        notes:
                output: true
                permalink: :title.html
defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: post
